Update TSC config to target ES2017
projecttacoma/fqm-execution pull request #140
Opened 2022-09-23 15:54 UTC by sarahmcdougall

# Summary
Updates the TS compiler config to target ES2017, which allows for the use of native async/await. Also updates the commit hash for the cql-execution dependency now that [https://github.com/projecttacoma/cql-execution/pull/20](https://github.com/projecttacoma/cql-execution/pull/20) has been merged.

## New behavior
N/A / better performance

## Code changes
Update tsconfig.json, update commit hash in package-lock for the cql-execution dependency

# Testing guidance
- Check that the commit hash for the cql-execution dependency matches the latest commit hash on the projecttacoma fork
- Run unit tests and other checks to make sure that nothing breaks 👍

2022-09-23 18:09 UTC, elsaperelli approved these changes
Looks good! Just one comment that may be irrelevant

2022-09-23 19:38 UTC, hossenlopp requested changes

2022-09-23 19:38 UTC, hossenlopp commented on tsconfig.json
>      "module": "commonjs",
Yes! Looking at the TSConfig docs, "CommonJS" is the proper option. https://www.typescriptlang.org/tsconfig#module

2022-09-23 20:03 UTC, hossenlopp approved these changes

2022-09-26 12:23 UTC, elsaperelli approved these changes
Nice!

2022-09-26 12:23 UTC, merged