Add support for PopulationBasis on a per-group basis
projecttacoma/fqm-execution pull request #141
Opened 2022-09-28 22:57 UTC by hossenlopp

# Summary

Now supports measures that define population basis on a per group basis.

## New behavior

Looks for the population basis extension on the group, if it doesn't exist it will fall back to looking at the measure.

## Code changes

`helpers/MeasureBundleHelpers.ts` - New function to look for population basis on the group.
`calculator/DetailedResultsBuilder.ts` - Make use of new function instead of existing one that looked at measure only.

# Testing guidance

Check slack for a bundle of a hacked together bundle.

2022-09-29 16:43 UTC, elsaperelli requested changes
Great work! Just two small comments :)

2022-09-29 17:25 UTC, sarahmcdougall requested changes
Good work! Tested on the edited bundle that has a second group, and tested with one group as well. I noticed the function coverage went down a little for `MeasureBundleHelpers.ts` so we might want to look into adding a unit test for this.

2022-09-29 19:09 UTC, hossenlopp commented on package-lock.json
> +      "version": "github:projecttacoma/cql-execution#36346a0fe1526abf48bfe8bdb37fe9e8164292bb",
Not sure how I accidentally downgraded it. Will look into reverting or making sure it is updated.

2022-10-03 18:38 UTC, hossenlopp commented on package-lock.json
> +      "version": "github:projecttacoma/cql-execution#36346a0fe1526abf48bfe8bdb37fe9e8164292bb",
Sorted this out. Had to nuke my node_modules to get it to update, very weird.

2022-10-03 18:38 UTC, hossenlopp commented on package-lock.json
> +      "version": "github:projecttacoma/cql-execution#36346a0fe1526abf48bfe8bdb37fe9e8164292bb",
Sorted this out. Had to nuke my node_modules to get it to update, very weird.

2022-10-03 19:04 UTC, elsaperelli approved these changes
Lgtm! Good addition of unit tests

2022-10-03 20:01 UTC, merged