Clause coverage highlighting for multiple groups
projecttacoma/fqm-execution pull request #170
Opened 2022-11-30 16:18 UTC by elsaperelli

# Summary
Before, the coverage highlighting only happened for one measure group. Now, it calculates the coverage for all patients for each individual group.

## New behavior
`generateClauseCoverageHTML` now returns a lookup object where the key is the groupId and the value is the clause coverage html for that group. There is an additional property on the CalculationOutput interface for `groupClauseCoverageHTML`. 

## Code changes
- `src/calculation/Calculator.ts`- The lookup object created by `generateClauseCoverageHTML` is now returned as part of the CalculationOutput in the `calculate` function. If the debug output is enabled, an html file for the overall clause coverage html is created and contains the html for each group. In addition, an html file is created for each of the groups clause coverage html.
- `src/Calculation/HTMLBuilder.ts`- `generateClauseCoverageHtml` iterates through each execution result and adds the detailedResult to a lookup object where the key is its corresponding groupId. Then, it iterates through that lookup object and calculates the clauseCoverageHtml for each of the groups in that lookup object. The html for each group is added to another lookup object where the key is the groupId and the value is the clause coverage html for that group. That lookup object is then returned.
- `src/types/Calculator.ts`- The optional `groupClauseCoverageHTML` property was added to the `CalculationOutput` interface.
- `test/HTMLGenerator.test.ts`- Tests were changed to reflect the changes to the return type of `generateClauseCoverageHTML`.
- `test/fixtures/html/SimpleCoverageAnnotation.html`- This file was modified to include the group name.
- `test/fixtures/html/SimpleCoverageAnnotation2.html`- This file was added for the unit test that tests `generateClauseCoverageHTML` on multiple groups.

# Testing guidance
1. `npm run check` to ensure that unit tests pass and there are no prettier or lint errors/warnings.
2. Using the files attached below, run the following command: `npm run cli -- detailed -m <path-to-measure-bundle.json> -p <path-to-pt1.json> <path-to-pt2.json> -o --debug`
3. Look at the html files in the debug directory. There should be 4 files: two for each group that includes that group's clause coverage and two for each group that includes that group's measure highlighting.
4. Let me know if you have any questions and more importantly if you have any suggestions for additional unit tests or testing methods. 

[coverage-test-case.zip](https://github.com/projecttacoma/fqm-execution/files/10125052/coverage-test-case.zip)

2022-12-01 14:12 UTC, natjoe4 requested changes
Just a couple small changes here. Functionality looks great in the provided example! Nice job

2022-12-02 20:55 UTC, mgramigna approved these changes

2022-12-02 23:20 UTC, natjoe4 requested changes
Good catch on the flatmap being unnecessary! Just a couple little linting issues

2022-12-02 23:20 UTC, natjoe4 commented on src/calculation/HTMLBuilder.ts
> +import { connect } from 'http2';
Looks like this snuck in in the last commit

2022-12-02 23:20 UTC, natjoe4 commented on src/calculation/HTMLBuilder.ts
> +    // uniqWith appears to pick the first element in encounters that matches the uniqueness condition
```suggestion
    // uniqWith appears to pick the first element it encounters that matches the uniqueness condition
```

2022-12-05 14:29 UTC, mgramigna commented on src/calculation/HTMLBuilder.ts
> +    // uniqWith appears to pick the first element in encounters that matches the uniqueness condition
Haha sorry

2022-12-05 14:30 UTC, mgramigna approved these changes

2022-12-05 16:14 UTC, natjoe4 approved these changes
Looks great!

2022-12-05 16:15 UTC, merged