Initial guidance
projecttacoma/fqm-execution pull request #234
Opened 2023-05-07 15:51 UTC by birick1

# Summary
Include a governance document describing issue workflow and dependency linking.

## New behavior
None - markdown updates.

## Code changes
New markdown file, and added section in contributing.md

# Testing guidance
None

2023-05-07 16:20 UTC, hossenlopp requested changes

2023-05-07 16:20 UTC, hossenlopp commented on governance.md
> +- An issue may be filed with no follow up activity from the submitter (e.g. more information is required, but not provided).  In this case, the issue will be closed and a new issue will need to be fi
We could use another bullet here for cases where the issue is actually a problem in `cql-execution` or the `cql-to-elm` translator. Often I think we could create tickets in those repositories. If it is a `cql-execution` issue we will create the ticket in the project and reference it. When the fix is released in `cql-execution` we will update our package's reference and update our version, then close the issue here.

2023-05-08 19:44 UTC, mgramigna approved these changes

2023-05-08 20:00 UTC, hossenlopp commented on governance.md
> +- An issue may be filed with no follow up activity from the submitter (e.g. more information is required, but not provided).  In this case, the issue will be closed and a new issue will need to be fi
Perfect!

2023-05-08 20:00 UTC, hossenlopp approved these changes

2023-05-09 13:24 UTC, merged