Order population expressions for HTML output
projecttacoma/fqm-execution pull request #260
Opened 2023-07-06 16:44 UTC by elsaperelli

# Summary
This is similar to Lauren's PR [here](https://github.com/projecttacoma/fqm-execution/pull/242) where we sorted the statements into population statements, non-functions, and then function statements; however, now we also order the population statements in the following order:

1. initial-population
2. denominator
3. denominator-exclusion
4. denominator-exception
5. numerator
6. numerator-exclusion
7. measure-population
8. measure-population-exclusion
9. measure-observation (alphabetically sorted if multiple)

...and then non-functions and function statements.

## New behavior
Population expression statements are now sorted in the above order. This order is based on the following "egg":
![image](https://github.com/projecttacoma/fqm-execution/assets/30158156/4a33c7bc-ece0-44bf-8ca4-38e1bff35507)

## Code changes
- `HTMLBuilder.ts` - I just added the sorting logic for the population expressions directly to the `sortStatements` function. Rather than using the `populationSet`, we now use `populationIdentifiers` because it includes the `code` (which is always the same) and the criteria expression (which can be different) for each population. That way we can sort statements because on what code their statement name links to.
- `HTMLBuilder.test.ts` - two new unit tests for `sortStatements()`- one for a proportion boolean measure (checks ordering of ipp, denom, numer) and one for a cv boolean measure (checks for ordering of ipp, measure population, measure population exclusion, measure observation function).

# Testing guidance
- `npm run check`
- I tested this in two ways:
1. I just ran calculation on as many measure bundles as I could find with the `--debug` flag and inspected the html output in the `debug/html` directory.
2. If you want to test certain cases, you can write your own CQL, bundle it with Matt's ecqm-bundler, and then run calculation on that to ensure the ordering is correct.

2023-07-10 14:48 UTC, lmd59 reviewed
Still doing testing, but something in my environment got a bit wonky, so leaving these code comments while I figure that one out!

2023-07-10 14:52 UTC, elsaperelli commented on README.md
> +![Screenshot of Population Venn Diagram](./static/population-diagram.png)
True! Do you remember where we originally found this lol

2023-07-10 17:19 UTC, mgramigna requested changes

2023-07-10 17:19 UTC, mgramigna commented on src/calculation/HTMLBuilder.ts
> +  const populationIdentifiers: Record<string, string> = {};
Quick comment saying that this is a lookup of cql expression identifier -> population type might be useful

2023-07-10 17:19 UTC, mgramigna commented on src/calculation/HTMLBuilder.ts
> +    if (Object.keys(populationIdentifiers).includes(b.statementName)) return 1;
`if(Object.keys(something).includes(k))` can almost always be replaced by `if(k in something)`

2023-07-11 16:36 UTC, lmd59 commented on src/calculation/HTMLBuilder.ts
> +  const populationOrder = [
This is the same order as the enum itself, so I think you can do
```suggestion
  const populationOrder = Object.values(PopulationType);
```
but if this throws off other things, feel free to ignore.

2023-07-11 18:54 UTC, lmd59 approved these changes

2023-07-12 13:48 UTC, mgramigna commented on src/calculation/HTMLBuilder.ts
> +  const populationOrder = Object.values(PopulationType);
hmmmm. Not sure I like relying on the iteration order of `Object.values` for a TypeScript enum. I think we should bring back the explicit ordering in a constant array.

2023-07-12 13:56 UTC, mgramigna approved these changes

2023-07-12 13:56 UTC, merged