Applies to stratifiers
projecttacoma/fqm-execution pull request #307
Opened 2024-07-17 14:41 UTC by elsaperelli

# Summary
This PR does two things: fixes an error that was occurring when running calculateMeasureReports on measure bundles whose group.stratifiers did not have `code.text` and adds functionality in measure report calculation for stratifiers that have the [cqfm-appliesTo extension](https://hl7.org/fhir/us/cqfmeasures/STU4/StructureDefinition-cqfm-appliesTo.html).

## New behavior
Measure report calculation no longer errors out with the measure bundle provided in the most recent fqm-execution issue- stratifiers are now either identified with `s.code` OR `s.id`. Additionally, if a stratifier has a `cqfm-appliesTo` extension, then only that associated population is included on the `stratifier.population` array in the MeasureReport. If the extension is not present, then the stratifier applies to all populations in the group. This specification is described in the [CQFM Computable Measure Profile](https://hl7.org/fhir/us/cqfmeasures/STU4/StructureDefinition-computable-measure-cqfm.html).

## Code changes
- `src/calculation/DetailedResultsBuilder.ts` - use `strata.id` if `strata.code.text` does not exist
- `src/calculation/MeasureReportBuilder.ts` - use `id` when setting up the population groups in the Measure Report, add `cqfm-appliesTo` extension functionality
- `test/unit/MeasureReportBuilder.test.ts` - unit tests for stratifiers with `cqfm-appliesTo`
- `test/unit/fixtures/measure/proportion-measure-with-stratifiers.json` - test measure with stratifiers that have the `cqfm-appliesTo extension`

# Testing guidance
- `npm run check`
- `npm run test:integration` & regression testing 
- Run MeasureReports with the measure bundle and patient provided in the fqm-execution issue. There are a couple ways to do this, but I use the cli in the following command: `npm run cli -- reports -m <measureBundle> -p <patientBundle> --debug -o -s 2025-01-01 -e 2025-12-31 --trust-meta-profile true`

2024-07-18 16:59 UTC, hossenlopp requested changes
Small change for report output.

I feel like this could use a test that adds results for two patients to make sure it properly makes use of the appliesTo (as we understand it now) and keeps with only having results for the single population on the stratifier output.

2024-07-18 16:59 UTC, hossenlopp commented on src/calculation/MeasureReportBuilder.ts
> +          reportStratifier.id = s.id ? s.id : '';
If there was no code or id on the stratification in the Measure resource, then there shouldn't be in the MeasureReport. Just add them to the stratifier if they exist.

2024-07-18 18:44 UTC, hossenlopp approved these changes

2024-07-19 15:55 UTC, lmd59 commented on src/calculation/MeasureReportBuilder.ts
> +                  group.stratifier?.find(s => s.id && s.id === stratResults.strataCode);
```suggestion
                  group.stratifier?.find(s => s.id === stratResults.strataCode);
```
Could be wrong if there's something weird about the stratResults, but I think that we don't need the extra `s.id` check here.

2024-07-19 15:56 UTC, lmd59 commented on src/calculation/MeasureReportBuilder.ts
> +                group.stratifier?.find(s => s.id && s.id === stratResults.strataCode);
```suggestion
                group.stratifier?.find(s => s.id === stratResults.strataCode);
```

2024-07-19 15:57 UTC, lmd59 reviewed
Just a small comment!

2024-07-19 16:19 UTC, lmd59 approved these changes

2024-07-19 17:22 UTC, merged