Library changes
projecttacoma/fqm-execution pull request #50
Opened 2021-04-07 15:48 UTC by MegRiley

Changes to support MAT generated measures that have URLs for the root…

# Summary
This change will now allow  for fqm execution to eventually support MAT generated measures that have urls as their root libraries instead of a fhir resource
## New behavior
This change should be transparent and the behavior shouldn't change
## Code changes
-execution.ts - changed the execute function to now check if a library is valid if it is either a fhir resource or a url
-measureHelpers.ts - added  a new method that accepts a string checks that this string is indeed a valid url (It may not be a valid library but that it is a valid url)
# Testing guidance
Using the debugger I ran this against EXM130 with the same patient  (the mat generated and the original version of the measrure in the 7.3.000 folder) I checked the that the elmLibraries = results.elmLibraries; was similar for both cases. (they were not identical, the libraries appeared to be in a different order and the MAT generated one included a mat specific library)

2021-04-08 17:16 UTC, okeefm requested changes
One place we may want to add some tests, but other than that looks good!

2021-04-08 17:16 UTC, okeefm commented on src/MeasureHelpers.ts
> +export function isValidLibraryURL(libraryName: string) {
We may want to add some positive/negative tests for this, if possible; something like calling `isValidLibraryURL` on `https://example.com/Library-url` and `Library/example` or the like, and ensuring the results are what we expect.

2021-04-08 18:12 UTC, mgramigna commented
## jest coverage report 🧪

### Total coverage

| Status | Category   | Percentage | Covered / Total |
| :----: | :--------- | :--------- | :-------------: |
|   🔴   | Statements | 28.34%     |     352/1242    |
|   🔴   | Branches   | 13.61%     |     215/1580    |
|   🔴   | Functions  | 24.68%     |      57/231     |
|   🔴   | Lines      | 28.37%     |     326/1149    |

> Status of coverage: 🟢 - ok, 🟡 - slightly more than threshold, 🔴 - under the threshold



<details><summary>Show files with reduced coverage 🔻</summary>


### Reduced coverage

| Status | Filename          | Statements         | Branches | Functions          | Lines              |
| :----: | :---------------- | :----------------- | :------- | :----------------- | :----------------- |
|   🔴   | src               | 25.08%             | 12.84%   | 21.27%             | 24.84%             |
|   🔴   | Execution.ts      | 7.87%              | 0%       | 0%                 | 8.43%              |
|   🟡   | MeasureHelpers.ts | 61.38% (-1.03% 🔻) | 68.53%   | 55.56% (-3.26% 🔻) | 61.42% (-1.18% 🔻) |

> Status of coverage: 🟢 - ok, 🟡 - slightly more than threshold, 🔴 - under the threshold


</details>

2021-04-09 13:12 UTC, okeefm approved these changes
Looks good!

2021-04-09 13:12 UTC, merged